// index.js
const { Client, GatewayIntentBits, SlashCommandBuilder } = require('discord.js');
const fs = require('fs');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent
  ]
});

const TOKEN = process.env.DISCORD_TOKEN;          // ← add this in Railway
const USED_KEYS_FILE = 'used_keys.json';          // simple file storage

// Load used keys (or create empty)
let usedKeys = {};
if (fs.existsSync(USED_KEYS_FILE)) {
  usedKeys = JSON.parse(fs.readFileSync(USED_KEYS_FILE, 'utf8'));
}

client.once('ready', async () => {
  console.log(`Logged in as ${client.user.tag}`);

  // Register slash command
  const command = new SlashCommandBuilder()
    .setName('generate-key')
    .setDescription('Generate a one-time key for the script');

  await client.application.commands.create(command);
  console.log('Slash command registered!');
});

client.on('interactionCreate', async interaction => {
  if (!interaction.isCommand()) return;

  if (interaction.commandName === 'generate-key') {
    // Optional: restrict to a role or specific users
    // if (!interaction.member.roles.cache.has('ROLE_ID_HERE')) {
    //   return interaction.reply({ content: 'You dont have permission!', ephemeral: true });
    // }

    // Generate simple key (you can make it fancier)
    const key = 'FED-' + Math.random().toString(36).substr(2, 9).toUpperCase() + '-' +
                Math.random().toString(36).substr(2, 9).toUpperCase();

    // Mark as unused
    usedKeys[key] = { used: false, generatedAt: Date.now(), user: interaction.user.tag };

    // Save to file
    fs.writeFileSync(USED_KEYS_FILE, JSON.stringify(usedKeys, null, 2));

    await interaction.reply({
      content: `Your key: **${key}**\n\nOne-time use only. Paste it in the script.\nExpires in 24h or after first use.`,
      ephemeral: true
    });

    // Optional: log to a channel
    const logChannel = client.channels.cache.get('YOUR_LOG_CHANNEL_ID');
    if (logChannel) {
      logChannel.send(`New key generated by ${interaction.user.tag}: ${key}`);
    }
  }
});

client.login(TOKEN);
